version: '3.8'
services:
    redis:
        image: redis
        ports: 
            - "6379:6379"
    demo_fastapi_plugin:
        image: demo_fastapi_plugin
        environment:
            - REDIS_TYPE=redis
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports:
            - "80:80"